const products = [
  {
    id: 1,
    name: "OnePlus Nord 2r Wireless Earbuds with Dual Mic",
    brand: "EcoShop",
    price: 32,
    originalPrice: 37,
    discount: 5,
    image: "/Images/asset 16.jpeg",
    HoverImage: "/Images/product-oneplus-hover.jpg",
    rating: 4,
  },
  {
    id: 2,
    name: "APPLE New AirPods Max Bluetooth Headset",
    brand: "MegaMart",
    price: 22.08,
    originalPrice: 24,
    discount: 2,
    image: "/Images/asset 10.jpeg",
    HoverImage: "/Images/product-airpods-hover.jpg",
    rating: 4,
  },
  {
    id: 3,
    name: "HP Smart Tank All-in-one WiFi Colour Printer",
    brand: "SmartShop",
    price: 225,
    originalPrice: 270,
    image: "/Images/asset 17.jpeg",
    HoverImage: "/Images/product-wifi-hover.jpg",
    rating: 4,
  },
  {
    id: 4,
    name: "Noise ColorFit Ultra 3 Smart Watch",
    brand: "SmartShop",
    originalPrice: 90,
    price: 78,
    image: "/Images/asset 19.jpeg",
    HoverImage: "/Images/product-smartwatch-hover.jpg",
    rating: 4,
  },
  {
    id: 5,
    name: "LG 8 kg Fully Automatic Top Load Washing Machine",
    brand: "TrendMart",
    price: 230,
    originalPrice: 236,
    discount: 6,
    image: "/Images/asset 18.jpeg",
    HoverImage: "/Images/product-Washingmachine-hover.jpg",
    rating: 5,
  },
  {
    id: 6,
    name: "iPhone 13, 128GB, Pink - Unlocked",
    brand: "Cartify",
    price: 194,
    originalPrice: 200,
    discount: 6,
    image: "/Images/asset 20.jpeg",
    HoverImage: "/Images/product-iphone-hover.jpg",
    rating: 4,
  },
  {
    id: 7,
    name: "Latest 4K Full HDR Smart Mi TV 138.8 Cm",
    brand: "Cartify",
    price: 190,
    originalPrice: 270,
    discount: 6,
    image: "/Images/asset 24.jpeg",
    HoverImage: "/Images/product-smartTV-hover.jpg",
    rating: 4,
  },
  {
    id: 8,
    name: `Apple MacBook Air 13.3" With Retina Display`,
    brand: "Cartify",
    price: 772,
    originalPrice: 972,
    discount: 6,
    image: "/Images/asset 25.jpeg",
    HoverImage: "/Images/product-macbook-hover.jpg",
    rating: 5,
  },
  {
    id: 9,
    name: "LG 8 kg Fully Automatic Top Load Washing Machine",
    brand: "TrendMart",
    price: 230,
    originalPrice: 236,
    discount: 6,
    image: "/Images/asset 18.jpeg",
    HoverImage: "/Images/product-Washingmachine-hover.jpg",
    rating: 4,
  },
  {
    id: 10,
    name: "iPhone 13, 128GB, Pink - Unlocked",
    brand: "Cartify",
    price: 194,
    originalPrice: 200,
    discount: 6,
    image: "/Images/asset 20.jpeg",
    HoverImage: "/Images/product-iphone-hover.jpg",
    rating: 4,
  },
  {
    id: 11,
    name: "HP Smart Tank All-in-one WiFi Colour Printer",
    brand: "SmartShop",
    price: 225,
    originalPrice: 270,
    image: "/Images/asset 17.jpeg",
    HoverImage: "/Images/product-wifi-hover.jpg",
    rating: 4,
  },
  {
    id: 12,
    name: "Latest 4K Full HDR Smart Mi TV 138.8 Cm",
    brand: "Cartify",
    price: 190,
    originalPrice: 270,
    discount: 6,
    image: "/Images/asset 24.jpeg",
    HoverImage: "/Images/product-smartTV-hover.jpg",
    rating: 4,
  },
];

export const ProductLegth = products.length;

export default products;

